### ISSUE TITLE
netcat still times out in face_atomic.py

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/ros-behavior-scripting#68] opened 2016-07-14 12:05 UTC
In face track if I update cogserver at 30 hz or 15 hz, netcat starts blocking and times out. I tries doing this by also just sending "(ConceptNode "12345678")" at 15 hz and it still causes netcat to time out and btree to stop

**Comment by yantrabuddhi** [comment] 2016-07-14 12:37
Test code to crash guile cogserver after stopping netcats from face_atomic.py

```
import time
from netcat import netcat
while (True):
    netcat("localhost",17020,"(ConceptNode (\"1234567\")\n")
    print "sent...\n"
    time.sleep(0.03)
```

**Comment by linas** [comment] 2016-07-14 18:36
OK, I can reproduce this.

**Comment by linas** [comment] 2016-07-16 18:05
pull requests opencog/opencog#2288  opencog/opencog#2289 opencog/opencog#2290  opencog/opencog#2291 resolve some of this issue.

There seems to be a memleak of some sort, as the cogserver keeps growing, and keeps getting slower. Trying to track that down.

**Comment by linas** [comment] 2016-07-16 21:00
I was wrong, there is non memleak -- valgrind confirms this. What was happening is that guile was slowly growing its heap; after a certain point, it settles down.

Note that the example program above has unbalanced parenthesis; this generates guile errors at a rate of 30/second. 

When the parenthesis are balanced, the system seems to mostly work most of the time, but I can still sometimes hang it -- specifically, in `boost::asio::recv` -- it hangs, waiting for data; I cannot tell why.  Investigating.

**Comment by linas** [comment] 2016-07-17 19:10
I think I eliminated the last of the crashes with pull request opencog/opencog#2296 

Please pull, recompile, and test, and close this bug if it starts working for you.

**Comment by linas** [comment] 2016-07-18 16:49
Mandeep reports that this is now working for him, am closing bug.

**Closed as completed by linas** 2016-07-18 16:49 UTC
Labels: bug
